### ISSUE TITLE
무슨 프로젝트입니까?

### ISSUE THREAD

**Issue by YWHyuk** [KangDroid/ROS_Manager#1]
서버 관리용 GUI프로그램인가용?

**Comment by KangDroid** [comment]
비슷해요!
연구팀 주제 중, 관리 관련 주제를 진행하게 되서 QT배워볼겸 한번 만들고 있습니다!

기본 서버 런칭은 ROS 기반으로 하고 있고, 아직 머릿속에서 설계/시뮬레이션 돌리고 있습니다! :)

**Comment by YWHyuk** [comment]
혼자 진행하는거니?

**Comment by KangDroid** [comment]
@YWHyuk 넵넵! 혼자 진행하고 있어요!

여기저기 다니고 있어서 좀 진행이 더디긴 한데 2월달까지 완성시키는게 목적입니다!

**Comment by YWHyuk** [comment]
흐음 재밌겠네 요즘 할만한 사이드 프로젝트 찾는 중이고 안부 물을겸 겸사겸사 물어봤어

**Comment by KangDroid** [comment]
@YWHyuk 넵넵!!
